apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: go-demo
  template:
    metadata:
      labels:
        run: go-demo
    spec:
      containers:
      - name: cngo
        image: volkan:cngo:latest
